name: BanAnnouncer
author: OopsieWoopsie
main: eu.mcdb.ban_announcer.bukkit.BanAnnouncerBukkit
version: 1.1.1-SNAPSHOT
depend: [Spicord]
description: Announce the punishments on your Discord server